version: '3'
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    cap_add: [ SYS_NICE ]
    environment:
      - MYSQL_DATABASE=microservices
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=devdojo
    volumes:
      - ./docker/volume_mysql:/var/lib/mysql  